/* =========================================================================
   settings.js — Setup screen: HomeKit pairing, discovered devices, health.
   ========================================================================= */
(function () {
  async function loadHomeKit() {
    try {
      const r = await fetch("/api/homekit");
      const hk = await r.json();
      document.getElementById("homekit-pin").textContent = hk.pin || "—";
      const box = document.getElementById("homekit-qr");
      if (hk.setup_uri) {
        // The authoritative pairing QR is generated by Home Assistant's HomeKit
        // Bridge (Settings > Devices > HomeKit). We render the setup PIN here
        // and link out; HA shows the scannable QR in its notifications.
        box.innerHTML =
          `<div style="color:#111;text-align:center;font:600 13px/1.4 sans-serif;padding:10px">
             Add to Apple Home<br><span style="font-size:26px;letter-spacing:2px">${hk.pin}</span>
             <br><span style="font-size:11px;color:#555">iPhone ▸ Home ▸ Add Accessory ▸ enter code</span>
           </div>`;
      }
    } catch (e) {
      console.warn("homekit load failed", e);
    }
  }

  async function loadDiscovered() {
    try {
      const r = await fetch("/api/discovered");
      const d = await r.json();
      const list = document.getElementById("discovered-list");
      list.innerHTML = "";
      if (!d.devices || !d.devices.length) {
        list.innerHTML = `<div class="muted">No scan yet. Tap “Re-scan”.</div>`;
        return;
      }
      d.devices.forEach((dev) => {
        const row = document.createElement("div");
        row.className = "disco-row";
        const ip = (dev.addresses || [])[0] || "";
        row.innerHTML = `<span>${dev.name || dev.service || "device"} <span class="badge">${ip}</span></span>
          <span class="badge">${dev.vendor || dev.source || ""}</span>`;
        list.appendChild(row);
      });
    } catch (e) {
      console.warn("discovered load failed", e);
    }
  }

  async function loadHealth() {
    try {
      const r = await fetch("/api/config");
      const cfg = await r.json();
      const el = document.getElementById("ha-status");
      el.textContent = cfg.ha_healthy ? "online" : "starting…";
      el.className = "dot " + (cfg.ha_healthy ? "ok" : "bad");
    } catch (e) {
      /* ignore */
    }
  }

  document.getElementById("rescan")?.addEventListener("click", async (e) => {
    e.target.textContent = "Scanning…";
    // trigger a re-scan via the backend if available, else just reload cache
    await fetch("/api/discovered");
    await loadDiscovered();
    e.target.textContent = "Re-scan network";
  });

  window.Settings = {
    load() { loadHomeKit(); loadDiscovered(); loadHealth(); },
  };
})();
