#!/usr/bin/env python3
"""First-run setup wizard for the SmartHome Touchscreen panel.

Runs on the Raspberry Pi's touch screen during install. It:
  * greets the user and explains what it needs,
  * prompts ONLY for the credentials that cannot be auto-discovered
    (Tuya/SmartLife QR sign-in, Eufy account, optional extras),
  * generates a HomeKit pairing PIN,
  * writes a `.env` file (chmod 600) the rest of the stack reads.

It is intentionally forgiving: every prompt has a sane default and can be
skipped, so the user can be "done in 1-5 minutes" and fill gaps later from the
dashboard Settings screen.

No secret is ever printed back to the screen or written anywhere but `.env`.
"""
from __future__ import annotations

import argparse
import os
import secrets
import shutil
import stat
from pathlib import Path

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt, Confirm
    _console = Console()
except Exception:  # pragma: no cover - fallback if rich missing
    _console = None


# --------------------------------------------------------------------------- #
# tiny prompt helpers that degrade gracefully without `rich`
# --------------------------------------------------------------------------- #
def say(msg: str, style: str = "") -> None:
    if _console:
        _console.print(msg, style=style)
    else:
        print(msg)


def banner(msg: str) -> None:
    if _console:
        _console.print(Panel.fit(msg, border_style="cyan"))
    else:
        print("\n" + "=" * 60 + f"\n{msg}\n" + "=" * 60)


def ask(label: str, default: str = "", password: bool = False) -> str:
    if _console:
        return Prompt.ask(label, default=default, password=password, show_default=not password)
    import getpass
    if password:
        return getpass.getpass(f"{label}: ") or default
    resp = input(f"{label} [{default}]: ").strip()
    return resp or default


def yes(label: str, default: bool = True) -> bool:
    if _console:
        return Confirm.ask(label, default=default)
    resp = input(f"{label} [{'Y/n' if default else 'y/N'}]: ").strip().lower()
    if not resp:
        return default
    return resp.startswith("y")


# --------------------------------------------------------------------------- #
# .env read / write
# --------------------------------------------------------------------------- #
def load_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env


def write_env(path: Path, env: dict[str, str]) -> None:
    lines = [
        "# Generated by first_run_setup.py — DO NOT COMMIT. Contains secrets.",
        "",
    ]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    path.write_text("\n".join(lines) + "\n")
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600
    say(f"[+] Wrote {path} (permissions 600)", style="green")


def _detect_timezone() -> str:
    """Best-effort local timezone so the clock is right out of the box."""
    try:
        from pathlib import Path as _P
        link = _P("/etc/localtime").resolve()
        parts = str(link).split("/zoneinfo/")
        if len(parts) == 2:
            return parts[1]
    except Exception:
        pass
    return os.getenv("TZ", "UTC")


def gen_homekit_pin() -> str:
    """Random 8-digit HomeKit PIN in XXX-XX-XXX form (avoids trivial codes)."""
    while True:
        digits = "".join(secrets.choice("0123456789") for _ in range(8))
        if len(set(digits)) > 1 and digits not in ("12345678", "00000000"):
            return f"{digits[0:3]}-{digits[3:5]}-{digits[5:8]}"


# --------------------------------------------------------------------------- #
# main flow
# --------------------------------------------------------------------------- #
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project-dir", default=os.path.expanduser("~/smarthome-touchscreen"))
    ap.add_argument("--noninteractive", action="store_true",
                    help="Accept all defaults (for automated re-installs).")
    args = ap.parse_args()

    root = Path(args.project_dir)
    env_path = root / ".env"
    example = root / ".env.example"
    marker = root / "setup" / ".setup_complete"

    # seed from existing .env, else from the example template
    env = load_env(env_path) or load_env(example)
    if not env and example.exists():
        shutil.copy(example, env_path)
        env = load_env(env_path)

    banner("SmartHome Touchscreen — First-Run Setup\n"
           "This takes about 2 minutes. Only a few passwords are needed;\n"
           "everything else is auto-discovered on your network.")

    if args.noninteractive:
        say("Non-interactive mode: keeping existing/default values.", style="yellow")
    else:
        # --- Location ------------------------------------------------------ #
        say("\n[1/6] Location & time (drives the clock and weather)", style="bold")
        env["TIMEZONE"] = ask("Timezone (IANA, e.g. America/New_York)",
                              env.get("TIMEZONE") or _detect_timezone())
        env["LATITUDE"] = ask("Latitude (optional, for weather/tides)", env.get("LATITUDE", ""))
        env["LONGITUDE"] = ask("Longitude (optional)", env.get("LONGITUDE", ""))

        # --- Tuya / SmartLife --------------------------------------------- #
        say("\n[2/6] Tuya / SmartLife (lights, strips, any SmartLife device)", style="bold")
        say("We use the QR-code 'Smart Life' sign-in — no developer account needed.")
        say("After setup finishes, open the dashboard Settings screen: it shows a")
        say("QR code to scan with the SmartLife app to link all Tuya devices.")
        if yes("Do you use the SmartLife / Tuya app?", default=True):
            env["TUYA_ENABLED"] = "true"
            code = ask("Optional: Tuya 'User Code' from SmartLife > Me > Settings (or blank)",
                       env.get("TUYA_USER_CODE", ""))
            env["TUYA_USER_CODE"] = code
        else:
            env["TUYA_ENABLED"] = "false"

        # --- WiZ ----------------------------------------------------------- #
        say("\n[3/6] WiZ bulbs", style="bold")
        say("WiZ bulbs are found automatically over the LAN — no password needed.")
        env["WIZ_AUTODISCOVER"] = "true"

        # --- Eufy ---------------------------------------------------------- #
        say("\n[4/6] Eufy Security cameras (optional, for live views)", style="bold")
        if yes("Do you have Eufy cameras to add?", default=False):
            env["EUFY_ENABLED"] = "true"
            env["EUFY_USERNAME"] = ask("Eufy account e-mail", env.get("EUFY_USERNAME", ""))
            pw = ask("Eufy password", password=True)
            if pw:
                env["EUFY_PASSWORD"] = pw
            env["EUFY_COUNTRY"] = ask("Country code", env.get("EUFY_COUNTRY", "US"))
        else:
            env["EUFY_ENABLED"] = "false"

        # --- Extras -------------------------------------------------------- #
        say("\n[5/6] Extra light strips (any brand with a local API)", style="bold")
        say("Most strips link through the SmartLife account above. If any strip")
        say("has a fixed IP with a local API, enter it (comma-separated) or skip.")
        env["EXTRA_LIGHT_HOSTS"] = ask("Extra light host IPs",
                                       env.get("EXTRA_LIGHT_HOSTS", ""))

        # --- Info panel (optional personalization) ------------------------ #
        say("\n[6/6] Rotating info panel (optional)", style="bold")
        say("Personalize the home screen's rotating panel. Leave blank to skip —")
        say("the clock always shows. You can change these later in Settings.")
        env["X_ACCOUNT"] = ask("X/Twitter handle to show (without @)",
                               env.get("X_ACCOUNT", "")).lstrip("@")
        if yes("Show tide/solunar panels for a coastal location?", default=False):
            say("Find your spot on tidespro.com and paste its page URL.")
            env["TIDES_WEEK_URL"] = ask("tidespro location URL",
                                        env.get("TIDES_WEEK_URL", ""))
            env["TIDES_MONTH_URL"] = ask("tidespro month URL (…/month)",
                                         env.get("TIDES_MONTH_URL", ""))
        else:
            env["TIDES_WEEK_URL"] = ""
            env["TIDES_MONTH_URL"] = ""

    # --- always-generated values ------------------------------------------ #
    if not env.get("HOMEKIT_PIN") or env.get("HOMEKIT_PIN") == "031-45-154":
        env["HOMEKIT_PIN"] = gen_homekit_pin()
    env.setdefault("HA_BASE_URL", "http://homeassistant:8123")
    env.setdefault("DASHBOARD_PORT", "8080")
    env.setdefault("SCREEN_WIDTH", "1920")
    env.setdefault("SCREEN_HEIGHT", "720")
    env.setdefault("TIMEZONE", _detect_timezone())
    if not env.get("TIMEZONE"):
        env["TIMEZONE"] = _detect_timezone()
    # Home Assistant needs numeric lat/long/elevation; default blanks to 0.
    for k in ("LATITUDE", "LONGITUDE", "ELEVATION"):
        if not (env.get(k) or "").strip():
            env[k] = "0"
    # Info-panel sources are personal — no defaults; blank means "hide panel".
    env.setdefault("X_ACCOUNT", "")
    env.setdefault("TIDES_WEEK_URL", "")
    env.setdefault("TIDES_MONTH_URL", "")
    env.setdefault("ROTATE_SECONDS", "10")

    write_env(env_path, env)
    marker.parent.mkdir(parents=True, exist_ok=True)
    marker.write_text("ok\n")

    banner("Setup saved!\n"
           f"HomeKit PIN for pairing all devices with Apple Home:\n"
           f"    {env['HOMEKIT_PIN']}\n"
           "You'll also see this as a QR code on the dashboard Settings screen.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
